version: "3"
services:
  channels:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-dev
    volumes:
      - ..:/app
    ports: ["5005:5005"]
    working_dir: /app
    command: ["run", "--debug"]

  actions:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-actions
    ports: ["5055:5055"]

  duckling:
    image: rasa/duckling
    ports: ["8000:8000"] 