version: "3"
services:
  rasa:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-dev
    command: ["run", "--debug", "--enable-api", "-m", "models"]
    container_name: rasa
    environment:
      - RASA_USER_APP
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
    ports: ["5005:5005"]
    volumes:
      - ..:/app

  action:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-action
    container_name: action
    ports: ["5055:5055"]

  duckling:
    image: rasa/duckling
    ports: ["8000:8000"] 