version: "3"
services:
  channels:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-channels
    command: ["run", "--debug", "--enable-api", "-m", "latest-model", "--remote-storage", "aws"]  
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_ENDPOINT_URL
      - AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME
      - RASA_USER_APP
      - RASA_X_HOST
      - RASA_X_TOKEN
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
    image: bespoken/rasa:channels
    ports: ["5005:5005"]
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:048661040156:secret:dockerhubAccessToken-C6jQ1R"
    
  actions:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-actions
    ports: ["5055:5055"]
    image: bespoken/rasa:actions
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:048661040156:secret:dockerhubAccessToken-C6jQ1R"
    
  duckling:
    image: rasa/duckling
    ports: ["8000:8000"]