version: "3"
services:
  channels:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-dev
    command: ["run", "--debug", "--enable-api", "-m", "latest-model", "--remote-storage", "aws"]
    container_name: channels
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - BUCKET_NAME
      - RASA_USER_APP
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
    ports: ["5005:5005"]
    volumes:
      - ..:/app

  actions:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-actions
    ports: ["5055:5055"]

  duckling:
    image: rasa/duckling
    ports: ["8000:8000"] 