version: "3"
services:
  rasa:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-rasa
    command: ["run", "--debug", "--enable-api", "-m", "latest-model", "--remote-storage", "aws"]  
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_ENDPOINT_URL
      - AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME
      - RASA_USER_APP
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
    image: bespoken/helpdesk-assistant-rasa
    ports: ["5005:5005"]
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:048661040156:secret:dockerhubAccessToken-C6jQ1R"
    
  action:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-action
    ports: ["5055:5055"]
    image: bespoken/helpdesk-assistant-action
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:048661040156:secret:dockerhubAccessToken-C6jQ1R"
    
  duckling:
    image: rasa/duckling
    ports: ["8000:8000"]