version: "3"
services:
  rasa-x:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-rasax
    command: ["rasa", "x", "--no-prompt", "--debug", "-m", "models", "--credentials", "credentials.yml"]
    environment:
      RASA_MODEL_SERVER: http://localhost:5005
      RASA_USER_APP: http://actions:5055
      RASA_TOKEN: RandomToken
      RASA_X_PASSWORD: ChangeThis!
      RASA_X_HOST: http://localhost:5002
      RASA_X_TOKEN: RandomToken
    image: bespoken/rasa:rasax
    ports: 
      - "5002:5002"
      - "5005:5005"
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:048661040156:secret:dockerhubAccessToken-C6jQ1R"
    
  actions:
    build: 
      context: ..
      dockerfile: docker/Dockerfile-actions
    ports: ["5055:5055"]
    image: bespoken/rasa:actions
    x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:048661040156:secret:dockerhubAccessToken-C6jQ1R"
    
  duckling:
    image: rasa/duckling
    ports: ["8000:8000"]