name: Deploy Rasa
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Install Docker ECS Integration CLI
      run: curl -L https://raw.githubusercontent.com/docker/aci-integration-beta/main/scripts/install_linux.sh | sh

    - name: Run Docker Compose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: bspk-rasa
        RASA_USER_APP: http://actions:5055
        RASA_X_HOST: http://channels:5005
      run: |
        docker context use default
        docker compose -f docker/docker-compose-rasa-ecs.yml build
        docker compose -f docker/docker-compose-rasa-ecs.yml push
        docker context use rasa
        docker compose -f docker/docker-compose-ecs.yml up

        
    