name: Test
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Rasa Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Run Local Containers
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        BUCKET_NAME: bspk-rasa
        RASA_USER_APP: https://actions:5055
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      run: |
        docker-compose -f docker/docker-compose-rasa-local.yml up

    - name: Run Tests
      run: |
        docker exec channels rasa test
