name: Test
on:
  push:
    paths:
      # We run this whenever the code or model changes
      - actions/*.py
      - channels/*.py
      - config.yml
      - data/**/*.md
      - domain.yml
    tags-ignore:
       # We don't want this to run on release
       - '**'

jobs:
  test:
    name: Rasa Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    # Build the model
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.9

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Train
      run: rasa train

    # Run the full set of containers (rasa, actions, duckling)
    - name: Run Local Containers
      env: 
        RASA_USER_APP: https://actions:5055
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      run: |
        docker-compose -f docker/docker-compose-local.yml up -d
        docker ps

    - name: Run Tests
      run: docker exec channels rasa test

    # We check the logs as a separate step, so we can see the errors if the previous step fails
    - name: Check logs
      if: ${{ cancelled() }}
      run: docker logs channels
