name: Train Model
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Train
      run: rasa train

    - name: Save Results
      uses: actions/upload-artifact@v1
      with:
        name: models
        path: models/

    - name: Upload Model
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: bspk-rasa
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'models'      # optional: defaults to entire repository